name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collectstatic
        run: |
          python manage.py collectstatic --noinput

      - name: Test Django-Q Cluster startup
        run: |
          timeout 10s python manage.py qcluster || echo "qcluster exited (expected for CI)"

      - name: Run Tests
        run: |
          python manage.py test
